### ISSUE TITLE
PMD fails on easy() configuration

### ISSUE THREAD

**Issue by Armaxis** [noveogroup/android-check#13]
Using the latest plugin _1.2.3_ when I configure PMD using `pmd { config easy() }` I get an exception:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mobile:androidPmd'.
> java.lang.IllegalArgumentException: Unable to exclude rules [UncommentedEmptyMethod]; perhaps the rule name is mispelled?
```

Stacktrace:

```
Caused by: java.lang.IllegalArgumentException: Unable to exclude rules [UncommentedEmptyMethod]; perhaps the rule name is mispelled?
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:116)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Task$perform.call(Unknown Source)
        at com.noveogroup.android.check.pmd.PmdCheck.performCheck(PmdCheck.groovy:60)
        at com.noveogroup.android.check.common.CommonCheck$_apply_closure2.doCall(CommonCheck.groovy:83)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 60 more
Caused by: java.lang.IllegalArgumentException: Unable to exclude rules [UncommentedEmptyMethod]; perhaps the rule name is mispelled?
        at net.sourceforge.pmd.RuleSetFactory.parseRuleSetReferenceNode(RuleSetFactory.java:348)
        at net.sourceforge.pmd.RuleSetFactory.parseRuleNode(RuleSetFactory.java:289)
        at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:242)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:176)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:171)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:135)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:119)
        at net.sourceforge.pmd.ant.internal.PMDTaskImpl.doTask(PMDTaskImpl.java:113)
        at net.sourceforge.pmd.ant.internal.PMDTaskImpl.execute(PMDTaskImpl.java:263)
        at net.sourceforge.pmd.ant.PMDTask.execute(PMDTask.java:46)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        ... 70 more
```

**Comment by Armaxis** [comment]
As of PMD 5.3.2 this rule [was deprecated](http://pmd.sourceforge.net/pmd-5.3.2/pmd-java/rules/java/design.html#UncommentedEmptyMethod) and `UncommentedEmptyMethodBody` should be used instead.

**Comment by igelgrun** [comment]
Thank you!

Fixed in 39a8737e74f4270b0aa8d119f446aa2cc5b0dc6b.
Release is coming soon.

**Comment by toonetown** [comment]
Any word on when the release will be available?

**Comment by letientai299** [comment]
While the release is not come out yet, are there any work around for this issue?

**Comment by alxndrsn** [comment]
Still hoping for a release or a workaround...

**Comment by alxndrsn** [comment]
@letientai299 to workaround, download https://github.com/noveogroup/android-check/blob/master/android-check-plugin/src/main/resources/pmd/pmd-easy.xml to `$projectRoot/config/pmd.xml`

**Comment by letientai299** [comment]
Thanks you, @alxndrsn .

**Comment by ultraon** [comment]
try to use following in buildscript section:

```
classpath ('com.noveogroup.android:check:1.2.3') {
            exclude module: 'checkstyle'
            exclude module: 'pmd-java'
        }
        classpath 'com.puppycrawl.tools:checkstyle:6.19'
        classpath 'net.sourceforge.pmd:pmd-java:5.5.1'
```

**Comment by Dushistov** [comment]
I see fix in master, any plans to release?

**Comment by smalichenko** [comment]
Released.
