### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: [Ljavax/annotation/meta/When;

### ISSUE THREAD

**Issue by fifa0329** [noveogroup/android-check#27]
:kepler:androidFindbugs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kepler:androidFindbugs'.
> Failed to run Gradle FindBugs Worker
   > [Ljavax/annotation/meta/When;

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':kepler:androidFindbugs'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.process.internal.worker.WorkerProcessException: Failed to run Gradle FindBugs Worker
        at org.gradle.process.internal.worker.WorkerProcessException.runFailed(WorkerProcessException.java:29)
        at org.gradle.process.internal.worker.request.Receiver.infrastructureFailed(Receiver.java:82)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$BoundedDispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$BoundedDispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:112)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
        ... 2 more
Caused by: java.lang.NoClassDefFoundError: [Ljavax/annotation/meta/When;
        at edu.umd.cs.findbugs.ba.jsr305.TypeQualifierAnnotation.<clinit>(TypeQualifierAnnotation.java:95)
        at edu.umd.cs.findbugs.FindBugs2.clearCaches(FindBugs2.java:318)
        at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:301)
        at org.gradle.api.plugins.quality.internal.findbugs.FindBugsExecuter.runFindbugs(FindBugsExecuter.java:39)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:87)
        at org.gradle.process.internal.worker.request.WorkerAction.runThenStop(WorkerAction.java:71)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.meta.When
        ... 11 more

BUILD FAILED

**Comment by fifa0329** [comment]
could anybody tell me why
and how to solve it
